"""Frozen daily trend/regime decision — the SINGLE source of truth.

These are exactly the rules validated in backtest/daily_regime_bt.py and
backtest/daily_regime_walkforward.py (200-SMA regime, rising slope + 3-month
momentum entry, 15% anti-chase, exit below the 200-SMA). The shadow paper runner
(ops/regime_shadow.py) imports THIS so the paper track record is generated by the
identical logic that was tested. tests/test_daily_regime.py pins the numbers.

Pure functions only. No I/O, no orders. Long-or-cash (TFSA, no shorting).
"""
from __future__ import annotations

from dataclasses import dataclass

SMA_LONG = 200
SLOPE_LOOKBACK = 20
MOM_LOOKBACK = 63
MAX_EXTENSION = 1.15   # never open a FRESH position >15% above the 200-SMA

# decisions
ENTER = "ENTER"           # cash -> go long at the next open
EXIT = "EXIT"             # long -> go to cash at the next open
STAY_LONG = "STAY_LONG"
STAY_CASH = "STAY_CASH"


@dataclass(frozen=True)
class RegimeInputs:
    close: float
    sma200: float
    sma200_prev: float      # SMA200 SLOPE_LOOKBACK days ago
    close_prev: float        # close MOM_LOOKBACK days ago
    ready: bool              # enough history for all three indicators


def inputs_from_closes(closes) -> RegimeInputs:
    """Build RegimeInputs from a chronological close series (list/tuple)."""
    n = len(closes)
    ready = n >= SMA_LONG + SLOPE_LOOKBACK  # need SMA today and SLOPE_LOOKBACK ago
    if n < SMA_LONG:
        return RegimeInputs(closes[-1] if n else 0.0, 0.0, 0.0, 0.0, False)
    sma200 = sum(closes[-SMA_LONG:]) / SMA_LONG
    sma200_prev = (sum(closes[-SMA_LONG - SLOPE_LOOKBACK:-SLOPE_LOOKBACK]) / SMA_LONG
                   if n >= SMA_LONG + SLOPE_LOOKBACK else 0.0)
    close_prev = closes[-MOM_LOOKBACK - 1] if n >= MOM_LOOKBACK + 1 else 0.0
    ready = ready and close_prev > 0
    return RegimeInputs(closes[-1], sma200, sma200_prev, close_prev, ready)


def decide(inp: RegimeInputs, state: str) -> str:
    """Map indicators + current state onto the one correct action.
    `state` is "LONG" or "CASH". Matches the backtest branch-for-branch."""
    if not inp.ready:
        return STAY_LONG if state == "LONG" else STAY_CASH
    if state == "CASH":
        enter = (inp.close > inp.sma200
                 and inp.sma200 > inp.sma200_prev
                 and inp.close > inp.close_prev
                 and inp.close <= MAX_EXTENSION * inp.sma200)
        return ENTER if enter else STAY_CASH
    # LONG
    return EXIT if inp.close < inp.sma200 else STAY_LONG
